services:
    bot:
        container_name: paperless-api-bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
    postgres:
        container_name: paperless-api-postgres
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_USER=paperless-api
            - POSTGRES_PASSWORD=5aefe7c33c1ece528783a813
            - POSTGRES_DB=paperless-api
        volumes:
            - postgres_data:/var/lib/postgresql/data
    redis:
        container_name: paperless-api-redis
        image: redis:latest
        command: [redis-server, --maxmemory-policy, noeviction]
        restart: unless-stopped
        volumes:
            - redis_data:/data
    minio:
        container_name: paperless-api-minio
        image: minio/minio:latest
        command: [minio, server, /data, --console-address, ':9001']
        restart: unless-stopped
        environment:
            - MINIO_ACCESS_KEY=paperless-api
            - MINIO_SECRET_KEY=5aefe7c33c1ece528783a813
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio_data:/data
        healthcheck:
            test: [CMD, mc, ready, local]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    postgres_data:
    redis_data:
    minio_data:

networks:
    default: {}
